### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by perkail** [vercel/nextjs-postgres-nextauth-tailwindcss-template#20]
Digest: 2721087

`[Error] Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

	(anonymous function) (159-0e028925908dd0d6.js:1:3426)
	ln (c93363e4-1a27167c75e65095.js:9:51367)
	(anonymous function) (c93363e4-1a27167c75e65095.js:9:51720)
	nf (c93363e4-1a27167c75e65095.js:9:27872)
	nd (c93363e4-1a27167c75e65095.js:9:27965)
	av (c93363e4-1a27167c75e65095.js:9:68621)
	ak (c93363e4-1a27167c75e65095.js:9:69271)
	aD (c93363e4-1a27167c75e65095.js:9:79905)
	ak (c93363e4-1a27167c75e65095.js:9:68946)
	aD (c93363e4-1a27167c75e65095.js:9:79905)
	ak (c93363e4-1a27167c75e65095.js:9:68946)
	aD (c93363e4-1a27167c75e65095.js:9:79905)
	ak (c93363e4-1a27167c75e65095.js:9:68946)
	aD (c93363e4-1a27167c75e65095.js:9:79905)
	ak (c93363e4-1a27167c75e65095.js:9:68946)
	aD (c93363e4-1a27167c75e65095.js:9:79905)
	ak (c93363e4-1a27167c75e65095.js:9:68946)
	aD (c93363e4-1a27167c75e65095.js:9:79905)
	ak (c93363e4-1a27167c75e65095.js:9:69619)
	aD (c93363e4-1a27167c75e65095.js:9:79905)
	ak (c93363e4-1a27167c75e65095.js:9:69315)
	(anonymous function) (c93363e4-1a27167c75e65095.js:9:102685)
	oU (c93363e4-1a27167c75e65095.js:9:103213)
	oE (c93363e4-1a27167c75e65095.js:9:88288)
	ok (c93363e4-1a27167c75e65095.js:9:87462)
	ok
	E (159-0e028925908dd0d6.js:25:1400)
	C (159-0e028925908dd0d6.js:25:1953)`

This is off of a clean deployment from Vercel's dashboard and all env are in place.

**Comment by link007** [comment]
This works for me, Install with npm instead pnpm, so:

Remove current modules
rm -rf node_modules package-lock.json

Install with npm
npm install

fix warnings
npm audit fix
npm audit fix --force
npm update --legacy-peer-deps
npm audit fix --legacy-peer-deps

and last stone in the shoe
npm uninstall @vercel/analytics

tips in vercel add env vars in Project Settings>Environment Variables
DATABASE_URL (get the url from planetscale and paste it without quotes)
NEXTAUTH_SECRET (generate in terminal with openssl rand -base64 32)
CI (false)

**Comment by noahlove** [comment]
To be clear: you need to also rename `.env.local.example` to `.env.local` if you haven't done that on initial install

**Comment by leerob** [comment]
I'll update the README to make this more clear!
