### ISSUE TITLE
"During the deployment, Vercel will prompt you to create a new Postgres database" this does not happen

### ISSUE THREAD

**Issue by Avivhdr** [vercel/nextjs-postgres-nextauth-tailwindcss-template#27]
There is no prompt to create a new database during deployment.

These are the actions that need to be done to have a working deployment + local development:
1. Click on the Deploy button on the [template page](https://vercel.com/templates/next.js/admin-dashboard-tailwind-postgres-react-nextjs) on vercel.
2. Completing the 3 steps:
   2.1 Creating a Repository.
   2.2 Adding 3 env variables.
       -- Github /oauth project: The user must create one if one doesn't exist. if one does exist, make sure that the `Homepage URL` and the `Authorization callback URL` are set correctly (not sure what is correctly setting it to the deployment URL also navigates there when logging in on a local env.)
   2.3 Deploy
 -- After deployment is completed, the app is broken. 
 3. Now the user must create a Postgres DB under the project (in Vercel)
 -- This solves the issue that brakes the app, but it require an additional deployment (I'm not aware of a "rebuild" button)
 4. The user should now clone the repository.
 5. Rename `.env.local.example` to `.env.local` and copy all the env variables to it from the project settings page on Vercel (`https://vercel.com/[USER_NAME]/admin-dashboard-tailwind-postgres-react-nextjs/settings/environment-variables`).
 6. Commit and push that change (this will trigger a rebuild and the app will work)
 7. Running `pnpm install` + `pnpm dev` 
 
 
 I guess that for many devs, most of it is obvious and doesn't require explanation, but for people (like myself) that take their first step with NextJS/Oauth/Postgres, these details instructions could be helpful to make this awsome template more reachable.
 
 I don't mind opening a PR to update the README file.

**Comment by sdfacre** [comment]
Thanks for your tips. however, on step 5, we shouldn't be storing the credentials on the file. Instead, they need to be added on vercel.

**Comment by leerob** [comment]
Thanks, I've updated the deployment URL to include the parameters to prompt to create a new Vercel Postgres instance.
