### ISSUE TITLE
Code: DEPLOYMENT_NOT_FOUND

### ISSUE THREAD

**Issue by CodeShr1mp** [vercel/nextjs-postgres-nextauth-tailwindcss-template#30]
When deploying app, all seems to be working. When I then sign in with Github, i get this error:

404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: arn1::7b9cd-1702853365073-ff67a4ed498d

Can someone please help!

**Comment by Avivhdr** [comment]
Does the sign-in work locally?
On the Github Oauth page, what are the parameters you entered on `Authorization callback URL` and `Homepage URL`?

**Comment by leerob** [comment]
Let me know if you're still seeing this!
