### ISSUE TITLE
Deleted `.env` example

### ISSUE THREAD

**Issue by nickelser** [vercel/nextjs-postgres-nextauth-tailwindcss-template#42]
Looks like you deleted the example `.env` file in https://github.com/vercel/nextjs-postgres-nextauth-tailwindcss-template/commit/5399727e34195375b7021f923b56b20cfa72bae0

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-postgres-nextauth-tailwindcss-template/commit/d82b4ce03d59e81bc87cc79d6186503b71e6da46
