### ISSUE TITLE
Login page get 404

### ISSUE THREAD

**Issue by patelvivekdev** [vercel/nextjs-postgres-nextauth-tailwindcss-template#43]
When clicking the login button on the navbar, it gets undefined on the URL and receives a 404 page.

![Screenshot 2024-04-18 163553](https://github.com/vercel/nextjs-postgres-nextauth-tailwindcss-template/assets/43227010/b1c07d77-e6c6-47e8-87fc-04e78ff3b7d5)

**Comment by jamesmurdza** [comment]
I ran into the same issue and deleting the NEXTAUTH_URL environment variable fixed it.

**Comment by abrambailey** [comment]
Would be nice to get some advice on this. What should we set NEXTAUTH_URL to? Also, in the github app what should we set Authorization callback URL to be? I'm also experiencing issues.

**Comment by patelvivekdev** [comment]
> Would be nice to get some advice on this. What should we set NEXTAUTH_URL to? Also, in the github app what should we set Authorization callback URL to be? I'm also experiencing issues.

You can set this callback URL in github OAuth.
```
https://example.com/api/auth/callback/github
```

**Comment by jamesmurdza** [comment]
@patelvivekdev I don't think your suggestion is clear. The callback URL that you set is the URL in your own app that the user should be redirected to after login.

**Comment by abrambailey** [comment]
I am trying to develop in localhost.

**Comment by jamesmurdza** [comment]
@patelvivekdev Never mind, your example was right. I tested this out and `/api/auth/callback/github` works.

So for @abrambailey it should be something like `http://localhost:3000/api/auth/callback/github`

**Comment by jamesmurdza** [comment]
I'm new to NextAuth and not familiar with how these callbacks work. I first guessed `https://example.com/` which also works, but I guess that doesn't check for any errors returned from the callback.

**Comment by jamesmurdza** [comment]
I've made two video tutorials on how to deploy this project, by the way:

- The first one forks this repository, then uses Vercel to deploy the GitHub repository: https://youtu.be/kIZ_AL3Wj8A

- The second just deploys directly from the Vercel templates page as a shortcut: https://youtu.be/EynGNuFtKeI

**Comment by leerob** [comment]
Thank you @jamesmurdza!

**Comment by jamesmurdza** [comment]
@leerob Sure! What was it exactly that you had to do to fix the demo? Just removing NEXTAUTH_URL?
