### ISSUE TITLE
Example file not found

### ISSUE THREAD

**Issue by avi-cenna** [vercel/nextjs-postgres-nextauth-tailwindcss-template#49]
I am currently trying to use the [Admin Dashboard Template](https://next-admin-dash.vercel.app/) template on Next.js, but I don't know where to get the environment variables. When I click Learn More (see image below) it takes me to this file, which doesn't exist anymore: https://github.com/vercel/nextjs-postgres-nextauth-tailwindcss-template/blob/main/.env.local.example.

![Screenshot 2024-05-13 at 5 17 18 PM](https://github.com/vercel/nextjs-postgres-nextauth-tailwindcss-template/assets/47500890/b84e3f82-2b27-4076-858f-e244bf69363e)

Thank you.

**Comment by leerob** [comment]
I will update this! 

https://github.com/vercel/nextjs-postgres-nextauth-tailwindcss-template/blob/main/.env.example
