### ISSUE TITLE
Errors on trying to login

### ISSUE THREAD

**Issue by hdennison** [vercel/nextjs-postgres-nextauth-tailwindcss-template#52]
Hello! I'm having some errors with the login process.

I cloned the repo, set up the database and updated `.env` file.

If I use the correct user/password I have in the database, the app works as expected.
If I use an incorrect user or incorrect password, the app crashes:

```
Unhandled Runtime Error
Error: Read more at https://errors.authjs.dev#credentialssignin

Source
app/login/page.tsx (19:13) @ async $$ACTION_0

  17 |           action={async (formData: FormData) => {
  18 |             'use server';
> 19 |             await signIn('credentials', {
...
```

IDK how helpful this can be, but just in case:
```
$ node -v
v20.11.1

**Comment by T04435** [comment]
Latest version of the template does use GitHub in `login/page.tsx`, not credentials.
Can you provide a reproduction.

**Comment by leerob** [comment]
^ Indeed, this repo has moved to use GitHub login 🙏
