### ISSUE TITLE
Depricated Packages

### ISSUE THREAD

**Issue by mdasiff** [vercel/nextjs-postgres-nextauth-tailwindcss-template#59]
I'm following readme, but not able to install due to below issue.

1. inflight: Remove depricated packages from package lock also
2. react@"19.0.0-rc.0: update this package

**Comment by leerob** [comment]
Could you please use `pnpm` to match the lockfile setup? I am not able to reproduce there. 

Relevant note from the docs on the prelease versions:

> If you see a peer dependencies warning, you may need to update react and react-dom to the suggested versions, or you use the --force or --legacy-peer-deps flag to ignore the warning. This won't be necessary once both Next.js 15 and React 19 are stable.
