### ISSUE TITLE
Invalid Redirect URI

### ISSUE THREAD

**Issue by db24dev** [vercel/nextjs-postgres-nextauth-tailwindcss-template#74]
Our current callback URI is https://ecominventoryperformanceinterface.vercel.app/api/auth/Github
We keep getting this error sign:
Be careful!
The redirect_uri is not associated with this application.
The application might be misconfigured or could be trying to redirect you to a website you weren't expecting.

**Comment by leerob** [comment]
Hey there, unfortunately I'm not sure the issue you are seeing with your fork of this template. I am not able to reproduce that issue on this domain.
